### ISSUE TITLE
Sync with prototype

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/au-kaleidos-css#8]
![image](https://user-images.githubusercontent.com/12690/115888935-c1776400-a453-11eb-853d-b67bdf872ec6.png)

A lot of CSS in the prototype has changed, that we need to sync over to the nain package. This in order to be able to implement new features such as the document card and uploader.

Todo: compare the SCSS folder of prototype with the SCSS folder of the package.

Release a new version of the package, maybe tagged with `beta.0` e.g. `1.20-beta.0` so it can be tested in https://github.com/kanselarij-vlaanderen/kaleidos-frontend/

**Comment by brenner-company** [comment]
### Status synchronisatie

- [ ] **_s-colors.scss**
  - [x] _@-master_ [04/05]: also replaced color variables inside component files
  - [ ] _@-development_
- [x] **_auk-avatar.scss**
  - [ ] _@-master_
  - [x] _@-development_ [05/05]
- [ ] **_auk-brand.scss**
  - [ ] _@-master_
  - [x] _@-development_ [05/05]: partly
- [x] **_auk-color-badge.scss**
  - [ ] _@-master_
  - [x] _@-development_ [05/05]
- [ ] **_auk-menu.scss**
  - [ ] _@-master_
  - [x] _@-development_ [05/05]: partly
- [ ] **_auk-sidebar.scss**
  - [x] _@-master_ [04/05]
  - [ ] _@-development_
